TW-1231 using x-api-key to generate QR code
tokoinofficial/t-chain-payment-sdk pull request #12
Opened 2022-12-27 11:26 UTC by vutrantokoin

Ticket: https://tokoin.atlassian.net/browse/TW-1231

Expected:
- generate QR code

2022-12-28 04:34 UTC, BinhNguyenTokoin requested changes
The sdk generates successfully but the my t wallet app crashed when scanning. I used dev branch for my t wallet 
![tchainQR](https://user-images.githubusercontent.com/57206348/209757786-59b41fe3-5219-4e46-81d2-8d596743b090.png)

https://user-images.githubusercontent.com/57206348/209757758-d3429b88-f3b6-4a68-b833-2c8ca1eb8568.mov

2022-12-29 11:26 UTC, vutrantokoin commented
The crash's fixed in https://github.com/tokoinofficial/tokoin_wallet/pull/417. Please check this PR again

2022-12-30 02:29 UTC, BinhNguyenTokoin commented on example/lib/utils/constants.dart
> +  static const String devApiKey = '3e093592-3e0e-4a52-9601-ead49f794586';
I think apiKey is a better name, user will receive prod api key from email and paste here. Using the devApiKey looks confused

2022-12-30 02:30 UTC, BinhNguyenTokoin approved these changes
Tested on dev full flow, tested on prod - stop at success to scan only 
Only one comment, fix that then we are good to carry on

2022-12-30 08:09 UTC, merged