TW-1121 Apply security for app to app and pos QR flow
tokoinofficial/t-chain-payment-sdk pull request #9
Opened 2022-10-14 06:29 UTC by vutrantokoin

Ticket: https://tokoin.atlassian.net/browse/TW-1121
Flow: https://swimlanes.io/u/rJQB5_aCn

Instead of generating data from SDK, we will get data that is generated from the server side
* SDK calls `generate-qrcode` API in both app-to-app and pos-qr-code case
* My T-Wallet will get the QR code from either a QR Image or deep link, then call API to get the respective merchant info

2022-10-17 07:56 UTC, BinhNguyenTokoin requested changes
Plz update read me with new flow images

2022-10-18 04:43 UTC, BinhNguyenTokoin requested changes
Please add padding between currency prefix with amount, then we can merge. 

![Screen Shot 2022-10-18 at 11 37 46](https://user-images.githubusercontent.com/57206348/196337216-24bbfd87-f77d-4676-99f5-855937fa3f3a.png)

2022-10-18 05:52 UTC, vutrantokoin commented
I have added a gap between the currency and the amount
![Screen Shot 2022-10-18 at 12 51 28](https://user-images.githubusercontent.com/82794492/196346534-b995f6c6-df24-4bb6-88cf-6361115354a2.png)

2022-10-18 07:52 UTC, BinhNguyenTokoin approved these changes

2022-10-18 10:42 UTC, merged